{"name": "Проверка невозможности возврата заказа при отсутствии трек-номера в запросе", "status": "passed", "steps": [{"name": "Получаем ID заказа по трек-номеру с произвольными данными", "status": "passed", "parameters": [{"name": "track_num", "value": "''"}], "start": 1733069179119, "stop": 1733069179162}], "start": 1733069179119, "stop": 1733069179162, "uuid": "4c18b352-23b6-47cd-b736-4423012c532b", "historyId": "3779ac802dfa1801a6a6569863cc658c", "testCaseId": "3779ac802dfa1801a6a6569863cc658c", "fullName": "tests.test_get_order_by_num.TestGetOrderByNum#test_get_order_without_num_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_num"}, {"name": "subSuite", "value": "TestGetOrderByNum"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "8820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_num"}]}