{"name": "Проверка невозможности принять заказ при некорректном ID курьера", "status": "passed", "steps": [{"name": "Создаём новый заказ и получаем его ID по трек-номеру", "status": "passed", "steps": [{"name": "Создаём новый заказ", "status": "passed", "parameters": [{"name": "color", "value": "None"}], "start": 1733062135523, "stop": 1733062135586}], "parameters": [{"name": "color", "value": "None"}], "start": 1733062135523, "stop": 1733062135739}, {"name": "Принимаем заказ по его ID и ID курьера с произвольными данными", "status": "passed", "parameters": [{"name": "order_id", "value": "384882"}, {"name": "courier_id", "value": "1000000"}], "start": 1733062135739, "stop": 1733062135814}], "start": 1733062135523, "stop": 1733062135815, "uuid": "9fefd894-fe31-4c45-ac3e-2181d04f195f", "historyId": "2187d1c5696e9555d5238263e2dc35ad", "testCaseId": "2187d1c5696e9555d5238263e2dc35ad", "fullName": "tests.test_take_order.TestTakeOrder#test_take_order_uncorrect_courier_id_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "14896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_take_order"}]}