{"name": "Проверка невозможности принять заказ, если он в работе", "status": "passed", "start": 1732976694350, "stop": 1732976695041, "uuid": "7e5d9ec7-39d7-4f5d-b0d9-930e5f5a4dbe", "historyId": "933b189cb3319187ef461b97af5132c5", "testCaseId": "933b189cb3319187ef461b97af5132c5", "fullName": "tests.test_take_order.TestTakeOrder#test_take_order_in_progress_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "10124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_take_order"}]}