{"name": "Проверка невозможности принять заказ при некорректном ID заказа", "status": "passed", "steps": [{"name": "Авторизуем курьера и возвращаем его ID", "status": "passed", "steps": [{"name": "Регистрируем нового курьера и возвращаем его логин, пароль, имя", "status": "passed", "start": 1733069184422, "stop": 1733069184466}], "start": 1733069184422, "stop": 1733069184520}, {"name": "Принимаем заказ по его ID и ID курьера с произвольными данными", "status": "passed", "parameters": [{"name": "order_id", "value": "1000000"}, {"name": "courier_id", "value": "427138"}], "start": 1733069184521, "stop": 1733069184574}], "start": 1733069184422, "stop": 1733069184575, "uuid": "42d283f5-ea99-46eb-97d9-7b5463a01136", "historyId": "98ac9120177e9e9034ab0d99562f962d", "testCaseId": "98ac9120177e9e9034ab0d99562f962d", "fullName": "tests.test_take_order.TestTakeOrder#test_take_order_uncorrect_order_id_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "8820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_take_order"}]}