{"name": "Проверка невозможности возврата заказа при отсутствии трек-номера в запросе", "status": "passed", "steps": [{"name": "Получаем ID заказа по трек-номеру с произвольными данными", "status": "passed", "parameters": [{"name": "track_num", "value": "''"}], "start": 1733062133169, "stop": 1733062133220}], "start": 1733062133169, "stop": 1733062133221, "uuid": "897216b2-aa27-445f-b457-d8bbfebb6027", "historyId": "3779ac802dfa1801a6a6569863cc658c", "testCaseId": "3779ac802dfa1801a6a6569863cc658c", "fullName": "tests.test_get_order_by_num.TestGetOrderByNum#test_get_order_without_num_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_num"}, {"name": "subSuite", "value": "TestGetOrderByNum"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "14896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_num"}]}